config/routes.rb
Rails.application.routes.draw do
  mount Shoppe::Engine => "/shoppe"

  root :to => 'pages#home'

  get 'procura' => 'search#index', :as => 'procura'

  #
  # Product browising
  #
  get 'produtos' => 'products#categories', :as => 'catalogue'
  get 'produtos/filter' => 'products#filter', :as => 'product_filter'
  get 'produtos/:category_id' => 'products#index', :as => 'products'
  get 'produtos/:category_id/:product_id' => 'products#show', :as => 'product'
  post 'produtos/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_secure_password

  validates :nome, :presence => true
  validates :sobrenome, :presence => true
  validates :email, :presence => true, uniqueness: {message: "Usu&aacute;rio j&aacute; cadastrado", case_sensitive: false}

  has_many :enderecos

  def nome_simples
    "#{nome}"
  end

  def nome_completo
    "#{nome} #{sobrenome}"
  end

  def reset_password
    self.password = SecureRandom.hex(8)
    self.password_confirmation = self.password
    self.save!
    #todo mandar email para cliente
    self.password
  end

  def self.authenticate(email, password)
    user = self.where(:email => email).first
    return false if user.nil?
    return false unless user.authenticate(password)
    user
  end
end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
  belongs_to :cliente

  validates :rua, :presence => true
  validates :numero, :presence => true
  validates :cep, :presence => true

end

app/models/product.rb
class Product < Shoppe::Product
  def path
    "produtos/#{self.product_category.permalink}/#{self.permalink}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/cliente_controller.rb
class ClienteController < ApplicationController
  def index
    @clientes = Cliente.all
  end

  def create
    @cliente = Cliente.new(:params)
  end
end

app/controllers/endereco_controller.rb
class EnderecoController < ApplicationController
  def index(id_cliente)
    @enderecos = Cliente.find(id_cliente).enderecos

  def create
    @endereco = Endereco.new(:params)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @products = Shoppe::Product.active.includes(:default_image, :product_category, :variants).root

    @clientes = Cliente.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter do
    if params[:category_id]
      @product_category = Shoppe::ProductCategory.where(:permalink => params[:category_id]).first!
    end
    if @product_category && params[:product_id]
      @product = @product_category.products.where(:permalink => params[:product_id]).active.first!
    end
  end

  def index
    @products = @product_category.products.includes(:default_image, :product_category, :variants).root.active
  end

  def filter
    @products = Shoppe::Product.active.with_attributes(params[:key].to_s, params[:value].to_s)
  end

  def categories
    @product_categories = Shoppe::ProductCategory.ordered.includes(:image)
  end

  def show
    @attributes = @product.product_attributes.public.to_a
  end

  def add_to_basket
    product_to_order = params[:variant] ? @product.variants.find(params[:variant].to_i) : @product
    current_order.order_items.add_item(product_to_order, params[:quantity].blank? ? 1 : params[:quantity].to_i)
    respond_to do |wants|
      wants.html { redirect_to request.referer }
      wants.json { render :json => {:added => true} }
    end
  rescue Shoppe::Errors::NotEnoughStock => e
    respond_to do |wants|
      wants.html { redirect_to request.referer, :alert => "We're sorry but we don't have enough stock to add that many products. We currently have #{e.available_stock} item(s) in stock. Please try again."}
      wants.json { render :json => {:error => 'NotEnoughStock', :available_stock => e.available_stock}}
    end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @products = Product.where('name like ?', "%#{params[:q]}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cliente_helper.rb
module ClienteHelper
end

app/helpers/endereco_helper.rb
module EnderecoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/compartilhado/_lista_produtos.html.haml
%ul.products
  -for product in products
    %li
      = link_to "#{root_url + product.path}" do
        .img{:style => product.default_image ? "background-image:url(#{product.default_image.path})" : ''}
      %p.info= truncate product.short_description, :length => 90
      %p= product.path
      %p.price= number_to_currency product.price

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title #{@page_title} - #{Shoppe.settings.store_name}
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield :head

  %body
    = render partial: "pages/header"

    %section.content.container
      .row
        .col-xs-12
          = yield

    = render partial: "pages/footer"

app/views/pages/_cart_header.html.haml
%p Seu carrinho está vazio

app/views/pages/_cliente_menu_header.html.haml
%ul
  %li= link_to "Minha Conta"
  %li= link_to "Cadastrar"
  %li= link_to "Meus Pedidos"

app/views/pages/_footer.html.haml
.news.container
  .row
    .col-xs-3
      %p Receba as novidades no seu email
    .col-xs-9
      %p form de news aqui, mailchimp

%footer
  .container
    .row
      .col-xs-3
        = render partial: "pages/footer/footer1"
      .col-xs-3
        = render partial: "pages/footer/footer2"
      .col-xs-3
        = render partial: "pages/footer/footer3"
      .col-xs-3
        = render partial: "pages/footer/footer4"
    .row
      .col-xs-12.text-center
        %h2 telefones
        %p Endereço
  .container-fluid.cnpj
    .container
      .row
        .col-xs-9
          %p
            #{Time.now.year} #{link_to "lojasnsp.com.br", root_path} Todos os
            direitos reservados | CNPJ: 09.237.611/0001-22
        .col-xs-3
          %p
            by #{link_to "OneSpace", "http://onespace.com.br", target: "_blank"}
            \& #{link_to "d3Group", "http://d3designdev.com/", target: "_blank"}

app/views/pages/_header.html.haml
%header.container
  .row.no-pad
    .col-xs-3
      %h1.logo
        = link_to root_path do
          = image_tag "logo.png"
    .col-xs-7
      = render partial: "pages/header/menu", locals: {categorias: Shoppe::ProductCategory.ordered}

    .col-xs-2
      %ul.links-uteis
        %li.cart
          %span.glyphicon.glyphicon-shopping-cart
          .conteudo
            = render partial: "pages/cart_header"
        %li.avatar
          %span.glyphicon.glyphicon-user
          .conteudo
            = render partial: "pages/cliente_menu_header"

    .col-xs-9
      = render partial: "pages/header/busca"

app/views/pages/footer/_footer1.html.haml
%h3 Mapa do Site
%p render header menu here

app/views/pages/footer/_footer2.html.haml
%h3 Acompanhe nossa loja
%p facebook
%p twitter

app/views/pages/footer/_footer3.html.haml
%h3 Confiança e Segurança
%p selos here

app/views/pages/footer/_footer4.html.haml
%h3 Formas de pagamento
%p formas de pagamento here

app/views/pages/header/_busca.html.haml
= form_tag("/procura", method: "get") do
  = button_tag(type: 'submit') do
    %i.glyphicon.glyphicon-search
  = text_field_tag(:q, params[:q], :placeholder => 'Pesquisar')

app/views/pages/header/_menu.html.haml
%nav{class: "navbar", role: "navigation"}
  %div.collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li.dropdown
        = link_to("" ,class: "dropdown-toggle", data: {toggle: "dropdown"}, role: "button") do
          Produtos
          %span.caret

        %ul{class: "dropdown-menu", role: "menu"}
          - for category in categorias
            %li= link_to category.name, category.permalink
      %li= link_to "Como Comprar"

app/views/pages/home.html.haml
- @page_title = "Bem vindo"

%p teste

- for product in @products
  = "nome do produto é #{product.name}"

%p teste customer

- for cliente in @clientes
  = "nome do cliente é #{cliente.nome_completo}"

app/views/products/show.html.haml
#produto
  .row
    .col-xs-4
      .imagem
        - if @product.default_image
          / todo, fazer uma galeria aqui
          .img{:style => "background-image:url(#{@product.default_image.path})"}
        - else
          .img{:style => "background-image:url(/images/produto-padrao.png)"}
    .col-xs-8
      %h3.titulo= @product.name
      .descricao-curta
        = truncate @product.short_description, :length => 180
        - if @product.has_variants?
          %table.variants
            - for variant in @product.variants
              %tr
                %td
                  - if variant.in_stock?
                    %p.stock.yes Disponível em estoque
                  - else
                    %p.stock.no Indisponível
                  %h4= variant.name
                  %p.price= number_to_currency variant.price
                %td.buy
                  = form_tag buy_product_path(@product.product_category.permalink, @product.permalink, :variant => variant.id), :class => (variant.in_stock? ? 'in-stock' : 'no-stock') do
                    %p
                      = select_tag 'quantity', options_for_select([1,2,3,4,5,6,7,8,9]), :disabled => !variant.in_stock?
                      = submit_tag 'Comprar', :disabled => !variant.in_stock?
        - else
          .optionsBox
            .top
              %p.price= number_to_currency @product.price
              = form_tag buy_product_path(@product.product_category.permalink, @product.permalink), :class => (@product.in_stock? ? 'in-stock' : 'no-stock') do
                %p
                  = select_tag 'quantity', options_for_select([1,2,3,4,5,6,7,8,9]), :disabled => !@product.in_stock?
                  = submit_tag 'Comprar', :disabled => !@product.in_stock?
            .bottom
              .stock
                - if @product.in_stock?
                  %p.yes Disponível em estoque
                - else
                  %p.no Indisponível
                  %p.time Sorry - we don't have any stock of this product at the moment. #{link_to "Let me know when you do"}.
              .links
                %ul
                  - if @product.data_sheet
                    %li.item.datasheet= link_to "Read product datasheet", @product.data_sheet.path

        - unless @attributes.empty?
          %table.attributes
            - for attribute in @attributes
              %tr
                %th= attribute.key
                %td= link_to attribute.value, product_filter_path(:key => attribute.key, :value => attribute.value)

        .calculo-frete
          %h5 Calcule o frete
          %p form de calculo de frete vai aqui
    .row
      .col-xs-12
        .description
          %h3 Descrição
          = @product.description.html_safe

app/views/search/index.html.haml
%h1.page-title
  Resultados de pesquisa para
  %span= params[:q]

- if @products.count > 0 then
  = render partial: "compartilhado/lista_produtos", locals: {products: @products}
- else
  %p nenhum resultado encontrado